### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by LecrisUT** [jaraco/jaraco.test#9]
Are there any blockers for tagging a new release? Right now I am only waiting on a release here (related to https://github.com/jaraco/skeleton/issues/138) to be able to package this for EPEL9. Maybe after #8 and related PRs are merged?

**Comment by LecrisUT** [comment]
@jaraco bump?

**Comment by jaraco** [comment]
Thanks for the ping. Happy to cut a release anytime. I'll review #8 and then cut a release.

**Comment by jaraco** [comment]
Done in 4dded77.
